{ DistributionList: 
   { Marker: '',
     MaxItems: 100,
     IsTruncated: false,
     Quantity: 13,
     Items: 
      [ { Id: 'E3T7KW2Z0UHNWA',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E3T7KW2Z0UHNWA',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:28:20.685Z,
          DomainName: 'dg5l6758bwg0x.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'd.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-driver-client-master',
                  DomainName: 'haulo-driver-client-master.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-driver-client-master',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'EP26M0WMSTQL0',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/EP26M0WMSTQL0',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:29:33.438Z,
          DomainName: 'd12k58tuuau7kh.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'a.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-admin-client-master',
                  DomainName: 'haulo-admin-client-master.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-admin-client-master',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'E3M7AD4LWA60YX',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E3M7AD4LWA60YX',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:25:33.530Z,
          DomainName: 'd1y8c3j2undrs8.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 't.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-trucking-client-master',
                  DomainName: 'haulo-trucking-client-master.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-trucking-client-master',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'E2WKVVTDD3P6S3',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E2WKVVTDD3P6S3',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:27:31.554Z,
          DomainName: 'd1cqmsittteyt9.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 's.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-shipping-client-master',
                  DomainName: 'haulo-shipping-client-master.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-shipping-client-master',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'E2RAIHM71YXFDY',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E2RAIHM71YXFDY',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:27:43.402Z,
          DomainName: 'd29yzec2tvf49a.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'ds.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-driver-client-staging',
                  DomainName: 'haulo-driver-client-staging.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-driver-client-staging',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'allow-all',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'ELMFHQ4FHWYOK',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/ELMFHQ4FHWYOK',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:29:06.925Z,
          DomainName: 'd29015h8i4w91m.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'as.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-admin-client-staging',
                  DomainName: 'haulo-admin-client-staging.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-admin-client-staging',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'E2HXHD0DTLH3RR',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E2HXHD0DTLH3RR',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:26:39.873Z,
          DomainName: 'd3vdzoue877edl.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'ss.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-shipping-client-staging',
                  DomainName: 'haulo-shipping-client-staging.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-shipping-client-staging',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'E2ODWCCR8R3NVF',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E2ODWCCR8R3NVF',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:26:13.965Z,
          DomainName: 'd3sxx8b0w5rree.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'ts.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-trucking-client-staging',
                  DomainName: 'haulo-trucking-client-staging.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-trucking-client-staging',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 0, Items: [] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'E1NODFDLDYD4UD',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E1NODFDLDYD4UD',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:27:04.504Z,
          DomainName: 'd2ohv73n0phtjk.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'sd.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-shipping-client-demo',
                  DomainName: 'haulo-shipping-client-demo.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-shipping-client-demo',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'E23LHGRAVPIBAE',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E23LHGRAVPIBAE',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:29:36.829Z,
          DomainName: 'd2jyz46dkz2wdc.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'ad.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-admin-client-demo',
                  DomainName: 'haulo-admin-client-demo.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-admin-client-demo',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'E1RM2G1TBNYOPR',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E1RM2G1TBNYOPR',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:27:57.824Z,
          DomainName: 'd1v72232dbu2sr.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'dd.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-driver-client-demo',
                  DomainName: 'haulo-driver-client-demo.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-driver-client-demo',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'E93IS59TT2TB5',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E93IS59TT2TB5',
          Status: 'Deployed',
          LastModifiedTime: 2018-05-08T08:25:57.212Z,
          DomainName: 'd3usnos4zqc50q.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'td.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-trucking-client-demo',
                  DomainName: 'haulo-trucking-client-demo.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-trucking-client-demo',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'redirect-to-https',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 0,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true },
        { Id: 'E2XOGNLH45DTX4',
          ARN: 'arn:aws:cloudfront::723698621383:distribution/E2XOGNLH45DTX4',
          Status: 'InProgress',
          LastModifiedTime: 2018-05-08T12:48:02.220Z,
          DomainName: 'd2n9yt5olsqm6.cloudfront.net',
          Aliases: { Quantity: 1, Items: [ 'at.haulo.co' ] },
          Origins: 
           { Quantity: 1,
             Items: 
              [ { Id: 'S3-haulo-admin-client-testing',
                  DomainName: 'haulo-admin-client-testing.s3.amazonaws.com',
                  OriginPath: '',
                  CustomHeaders: { Quantity: 0, Items: [] },
                  CustomOriginConfig: 
                   { HTTPPort: 80,
                     HTTPSPort: 443,
                     OriginProtocolPolicy: 'https-only',
                     OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
                     OriginReadTimeout: 30,
                     OriginKeepaliveTimeout: 5 } } ] },
          DefaultCacheBehavior: 
           { TargetOriginId: 'S3-haulo-admin-client-testing',
             ForwardedValues: 
              { QueryString: false,
                Cookies: { Forward: 'none' },
                Headers: { Quantity: 1, Items: [ 'Origin' ] },
                QueryStringCacheKeys: { Quantity: 0, Items: [] } },
             TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
             ViewerProtocolPolicy: 'allow-all',
             MinTTL: 0,
             AllowedMethods: 
              { Quantity: 7,
                Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
                CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
             SmoothStreaming: false,
             DefaultTTL: 86400,
             MaxTTL: 31536000,
             Compress: false,
             LambdaFunctionAssociations: { Quantity: 0, Items: [] },
             FieldLevelEncryptionId: '' },
          CacheBehaviors: { Quantity: 0, Items: [] },
          CustomErrorResponses: { Quantity: 0, Items: [] },
          Comment: '',
          PriceClass: 'PriceClass_All',
          Enabled: true,
          ViewerCertificate: 
           { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             SSLSupportMethod: 'sni-only',
             MinimumProtocolVersion: 'TLSv1.1_2016',
             Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
             CertificateSource: 'acm' },
          Restrictions: 
           { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
          WebACLId: '',
          HttpVersion: 'HTTP1_1',
          IsIPV6Enabled: true } ] } }
