{ Id: 'E3T7KW2Z0UHNWA',
  ARN: 'arn:aws:cloudfront::723698621383:distribution/E3T7KW2Z0UHNWA',
  Status: 'Deployed',
  LastModifiedTime: 2018-04-26T15:41:19.367Z,
  DomainName: 'dg5l6758bwg0x.cloudfront.net',
  Aliases: { Quantity: 1, Items: [ 'd.haulo.co' ] },
  Origins: 
   { Quantity: 1,
     Items: 
      [ { Id: 'S3-haulo-driver-client-master',
          DomainName: 'haulo-driver-client-master.s3.amazonaws.com',
          OriginPath: '',
          CustomHeaders: { Quantity: 0, Items: [] },
          CustomOriginConfig: 
           { HTTPPort: 80,
             HTTPSPort: 443,
             OriginProtocolPolicy: 'https-only',
             OriginSslProtocols: { Quantity: 2, Items: [ 'SSLv3', 'TLSv1' ] },
             OriginReadTimeout: 30,
             OriginKeepaliveTimeout: 5 } } ] },
  DefaultCacheBehavior: 
   { TargetOriginId: 'S3-haulo-driver-client-master',
     ForwardedValues: 
      { QueryString: false,
        Cookies: { Forward: 'none' },
        Headers: { Quantity: 1, Items: [ 'Origin' ] },
        QueryStringCacheKeys: { Quantity: 0, Items: [] } },
     TrustedSigners: { Enabled: false, Quantity: 0, Items: [] },
     ViewerProtocolPolicy: 'redirect-to-https',
     MinTTL: 0,
     AllowedMethods: 
      { Quantity: 7,
        Items: [ 'HEAD', 'DELETE', 'POST', 'GET', 'OPTIONS', 'PUT', 'PATCH' ],
        CachedMethods: { Quantity: 2, Items: [ 'HEAD', 'GET' ] } },
     SmoothStreaming: false,
     DefaultTTL: 86400,
     MaxTTL: 31536000,
     Compress: false,
     LambdaFunctionAssociations: { Quantity: 0, Items: [] },
     FieldLevelEncryptionId: '' },
  CacheBehaviors: { Quantity: 0, Items: [] },
  CustomErrorResponses: { Quantity: 0, Items: [] },
  Comment: '',
  PriceClass: 'PriceClass_All',
  Enabled: true,
  ViewerCertificate: 
   { ACMCertificateArn: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
     SSLSupportMethod: 'sni-only',
     MinimumProtocolVersion: 'TLSv1.1_2016',
     Certificate: 'arn:aws:acm:us-east-1:723698621383:certificate/b46c1298-9e80-4bbf-9615-55b9a62a7f21',
     CertificateSource: 'acm' },
  Restrictions: 
   { GeoRestriction: { RestrictionType: 'none', Quantity: 0, Items: [] } },
  WebACLId: '',
  HttpVersion: 'HTTP1_1',
  IsIPV6Enabled: true }
